drop  table if exists films;
drop  table if exists users;
drop  table if exists rents;
create table Films(ID INT PRIMARY KEY AUTO_INCREMENT, Title varchar(400), Copies int, Requested int, Approved bool);
create table Users(ID INT PRIMARY KEY AUTO_INCREMENT, Username varchar(600), Admin bool);
create table Rents(ID INT PRIMARY KEY AUTO_INCREMENT, UserId int, FilmId int, Rented DATETIME, Returned datetime);
insert into videorental.films (Title, Copies, Requested, Approved) VALUES ("Spartacus", 3, 0, 1);
insert into videorental.films (Title, Copies, Requested, Approved) VALUES ("The Shining", 3, 0, 1);
insert into videorental.films (Title, Copies, Requested, Approved) VALUES ("2001 a space odyssey", 3, 0, 1);
insert into videorental.films (Title, Copies, Requested, Approved) VALUES ("A clockwork orange", 3, 0, 1);
insert into videorental.films (Title, Copies, Requested, Approved) VALUES ("Eyes whide shut", 3, 0, 1);
insert into videorental.films (Title, Copies, Requested, Approved) VALUES ("Full metal Jacket", 3, 0, 1);
insert into videorental.films (Title, Copies, Requested, Approved) VALUES ("Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", 3, 0, 1);
insert into videorental.films (Title, Copies, Requested, Approved) VALUES ("Lolita", 3, 0, 1);
insert into videorental.users (Username, Admin) VALUES ("Stanley", 0);
insert into videorental.users (Username, Admin) VALUES ("Kubrick", 1);
insert into videorental.rents (UserId, FilmId, Rented, Returned) VALUES (1,1, NOW(), null);
insert into videorental.rents (UserId, FilmId, Rented, Returned) VALUES (1,2, NOW(), null);
insert into videorental.rents (UserId, FilmId, Rented, Returned) VALUES (1,1, NOW(), NOW()+1);
insert into videorental.rents (UserId, FilmId, Rented, Returned) VALUES (1,1, NOW(), null);
insert into videorental.users (Username, Admin) VALUES ("Jack", 0);
