package com.filmrental.SOAPWS.service;

import java.util.logging.Logger;

/**
 * Examples code for spring boot with CXF services. HelloPortImpl is the
 * implementation for Hello interface. This class was generated by Apache CXF
 * 3.1.0 2015-05-18T13:02:03.098-05:00 Generated source version: 3.1.0
 */

@javax.jws.WebService(serviceName = "HelloService", portName = "HelloPort",
                    targetNamespace = "http://service.ws.sample/",
                    endpointInterface = "com.filmrental.SOAPWS.service.Hello")
public class HelloPortImpl implements Hello {

    private static final Logger LOG = Logger.getLogger(HelloPortImpl.class.getName());

    public String sayHello(String myname) {
        LOG.info("Executing operation sayHello" + myname);
        
            return "Hello, Welcome to CXF Spring boot " + myname + "!!!";
    }

}